### ISSUE TITLE
Applied Logic Tree gets reverted when not modifying the tree after applying

### ISSUE THREAD

**Issue by IzaZed** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#1]
When applying a logic tree to an object, the user has to move, add or remove any node to prevent the tree from being removed after exiting Play Mode.

**Comment by IzaZed** [comment]
Well, that was dumb
UPBGE has an option "Undo at Exit" which is enabled by default - this was caused by an actual feature.

**Comment by youle31** [comment]
Hello, i'm an upbge contributor. Actually, undo at exit is enabled by default because upbge-eevee is using original viewport data. I manually revert the position of all the objects at ge exit but, for example, if you modify the mesh with bpy and that you don't undo at exit, the mesh will remain as it was at bge runtime.

This is why undo at exit is very often useful and enabled by default.

Normally I do an Undo Push at bge start (After that you pressed P key) and I apply undo at bge exit (when you press escape). I don't exactly know where your issue comes from but maybe when you are applying your logic tree, you have to do an undo push if it is missing? If i take a random addon I see:
bl_options = {'REGISTER', 'UNDO'} just below Class definition

**Comment by IzaZed** [comment]
Ah okay, I just noticed that it doesn't happen when the option is unchecked

Same goes for indirect light baking - the lighting cache is reverted when it's checked but stays when it's unchecked... for now i'll have to leave it the way it is
