### ISSUE TITLE
always need click apply to selected

### ISSUE THREAD

**Issue by mushroomeo** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#15]
the logic nodes loses effect on object if not clicking on apply to selected button everytime quit and rerun BGE

found out / remembered that need to move the logic nodes after click apply to selected button and then run BGE then it dont need to click again next time on apply to selected button.

this is really annoying / confusing

**Comment by IzaZed** [comment]
This is something that I need to investigate, though the same thing happens when baking indirect lighting for example - when starting the game directly after baking indirect lighting and exiting the engine, the lighting cache is lost
This has something to do with the "Undo At Exit" option which is needed to revert the scene to it's original status

I'll take a look

**Comment by youle31** [comment]
I'm far from being an expert in addons, and i'm not sure this can help... but I think adding this:

bl_options = {'REGISTER', 'UNDO'} in some classes inherited from bpy.types.Operator

could solve some issues related to undo at exit.

For example, I took a screenshot of a random addon picked in release/scripts:

![Capture](https://user-images.githubusercontent.com/10052509/78250755-a35d5f80-74f0-11ea-9c79-21c2fd58a57b.PNG)

**Comment by IzaZed** [comment]
Yeeeehs that was it! I had it in there but at the wrong place, whoopsidoodle

Thanks youle!
