### ISSUE TITLE
the add object node is not working 

### ISSUE THREAD

**Issue by ElioOnPC** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#29]
that's my set up 
![upbge](https://user-images.githubusercontent.com/63975613/86503937-0aedaa00-bd81-11ea-8f00-1bd8d1b8a65b.png)

**Comment by IzaZed** [comment]
This is a little tricky since the way scenes and collections work in 2.8 is a bit different from the way it was before. You need to enter the name of an object that is **in an active collection, but set to invisible**

The way I do this is add all objects to a collection "AddedObjects" and simply hide everything in there

I updated the Node a little so that you can now set a reference object whose position/scale etc. will be applied to the added object 🙂

**Comment by ElioOnPC** [comment]
Is that part of the 0.8.9 release or is it for the next release

**Comment by IzaZed** [comment]
Its technically the next release, but the state of the addon gets continuously merged into upbge's addons, so it'll be in the current alpha builds :)

**Comment by IzaZed** [comment]
I'll close this now, if the error persists, feel free to re-open it
