### ISSUE TITLE
UPBGE0.3.0 Property Problem and sound problem

### ISSUE THREAD

**Issue by spooptrapdevil** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#34]
now i know this is not an issue but its an pull request can you please add: assign, add, copy property's?
and add the others like the: equal property cause i am having a problem doing that or are they already in? but please add this and the sound has some wrong node pull of the orange last sound dot pull it does nothing i dont know if you maybe still working on it or maybe you did not add any code to with but if you add this thanks i know for sure you are working so hard on this but i hope the best!

**Comment by IzaZed** [comment]
Alright, I added in an "Evaluate Property" Node that mimics what the property sensor does 🙂 I think that was what you were looking for, right?
Copy From Object looks for the property in the second object and creates a new property with the same value on the first object

The sound nodes actually did work as intended, the sound handle was only retrievable in the frame the sound was activated, but I changed it now so that the socket can be used as long as the sound plays 👍 

Same goes for vehicle now

As for Assign property, that's called "Set Property" in Nodes, add is "Add To Property" (also accepts negative values for substraction)

Let me know if I missed something 🙂
